version: 1.0.{build}

before_build:
- ps: nuget restore ./AquaWorld/AquaWorld.sln

build:
  project: ./AquaWorld/AquaWorld.sln
  verbosity: minimal

environment:
    COVERALLS_REPO_TOKEN:  
       secure: dWTMEyppw6+k1jtfvkZP6D8IcGzfWxk22rz0iMG2fND3RO6IT7yMEui9D4LeB39Z

after_test: 
    - AquaWorld\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"AquaWorld\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single  AquaWorld\AquaWorld.Tests\bin\debug\AquaWorld.Tests.dll" -output:coverage.xml

    - AquaWorld\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml